### ISSUE TITLE
Do add-ons belong inside kube-system namespace?

### ISSUE THREAD

**Issue by anarsen** [nuuday/terraform-aws-eks-addons#12]
# Problem

Components such as cert-manager and external-dns create ServiceAccounts. They are bound to different roles within the namespace they are in.

It's not uncommon to see rules such as

```yaml
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  verbs:
  - get
```

If coredns, aws-node, cert-manager, external-dns and all the other components run within the same namespace, we will give ServiceAccounts unnecessary access to Secrets etc.
